### ISSUE TITLE
error-麻烦作者帮忙看下是哪里的问题

### ISSUE THREAD

**Issue by Vainycos** [wangwenxi-handsome/bilibili-bullet-chat-game#3]
启动报错：Traceback (most recent call last):
  File "C:\project\do\bilibili-bullet-chat-game\blivedm\client.py", line 471, in _on_ws_message
    await self._parse_ws_message(message.data)
  File "C:\project\do\bilibili-bullet-chat-game\blivedm\client.py", line 519, in _parse_ws_message
    await self._handle_command(body)
  File "C:\project\do\bilibili-bullet-chat-game\blivedm\client.py", line 573, in _handle_command
    asyncio.gather(
TypeError: gather() got an unexpected keyword argument 'loop'

**Comment by wangwenxi-handsome** [comment]
hi，看起来是python版本的问题，请问你的python版本是？

**Comment by Vainycos** [comment]
之前用的旧电脑，具体版本有点忘了；好像是3.9，有版本要求吗，具体需要哪个版本我可以再试试

**Comment by wangwenxi-handsome** [comment]
我猜之前应该是3.10，保险一些3.8及以下都可以

**Comment by akirahayabusa** [comment]
[21550509] 当前人气值：1
room=21550509 unknown cmd=LOG_IN_NOTICE, command={'cmd': 'LOG_IN_NOTICE', 'data': {'notice_msg': '为保护用户隐私，未登录无法查看他人昵称', 'image_web': 'http://i0.hdslb.com/bfs/dm/75e7c16b99208df259fe0a93354fd3440cbab412.png', 'image_app': 'http://i0.hdslb.com/bfs/dm/b632f7dcd3acf47deffb5f9ccc9546ae97a3415b.png'}}

加入游戏没有反应是怎么回事呢

**Comment by akirahayabusa** [comment]
总之地图上一片空白，啥也没有，只有六边形。
